# Generated by Django 5.1.5 on 2025-02-10 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_informacoe_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informacoe',
            new_name='Informacoes',
        ),
        migrations.AlterModelOptions(
            name='informacoes',
            options={'verbose_name_plural': 'Informações'},
        ),
    ]
