# Generated by Django 5.1.5 on 2025-02-07 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_alter_disciplinas_thumb'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinas',
            old_name='disciplina',
            new_name='eixo',
        ),
        migrations.RemoveField(
            model_name='aulas',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='aulas',
            name='mapasTexto',
        ),
        migrations.AddField(
            model_name='mapastexto',
            name='aula',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.aulas'),
        ),
        migrations.AddField(
            model_name='mapastexto',
            name='x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='mapastexto',
            name='y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='avaliacoe',
            name='aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.aulas'),
        ),
        migrations.AlterField(
            model_name='avaliacoe',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
