# Generated by Django 5.1.5 on 2025-02-10 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_rename_disciplina_disciplinas_eixo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avaliacoe',
            new_name='Avaliacoes',
        ),
        migrations.RenameModel(
            old_name='EixosTematico',
            new_name='EixosTematicos',
        ),
        migrations.RenameModel(
            old_name='MapasTexto',
            new_name='MapasTextos',
        ),
        migrations.AlterModelOptions(
            name='aulas',
            options={'verbose_name_plural': 'Aulas'},
        ),
        migrations.AlterModelOptions(
            name='disciplinas',
            options={'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='eixostematicos',
            options={'verbose_name_plural': 'Eixos Temáticos'},
        ),
        migrations.AlterModelOptions(
            name='mapastextos',
            options={'verbose_name_plural': 'Mapas Textos'},
        ),
        migrations.AlterModelOptions(
            name='temas',
            options={'verbose_name_plural': 'Temas'},
        ),
    ]
