# Generated by Django 5.1.5 on 2025-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0005_rename_avaliacoe_avaliacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aulas',
            name='duracao',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='aulas',
            name='mapa',
            field=models.ImageField(upload_to='mapa_aula'),
        ),
    ]
