# Generated by Django 5.1.5 on 2025-02-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0006_aulas_duracao_alter_aulas_mapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='aula',
            field=models.CharField(),
        ),
    ]
