# Generated by Django 5.1.5 on 2025-02-14 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0007_alter_aulas_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapastextos',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.aulas'),
        ),
    ]
